### ISSUE TITLE
Querying with multiple jsob_containers

### ISSUE THREAD

**Issue by DavidHooper** [jrochkind/json_attribute#2]
Does the query interface currently support querying with multiple jsonb_containers. 

An example would I've got 2 jsonb columns in my table. One named `data` the other named `something_data`.

How can I query `something_data` and not `data`?

Thanks

**Comment by jrochkind** [comment]
Yes, it should. You specify the underlying column a json_attribute is in when you declare it, and then just specify the json_attributes you want to query, it should figure out the right column to address on it's own. You can even mix and match within the same query. Will you try it and let me know if you have any trouble?
