### ISSUE TITLE
Model serializable hash keys with store key as oppose to name

### ISSUE THREAD

**Issue by onomated** [jrochkind/json_attribute#4]
Looks like this is by design in the [JsonAttribute::Model](https://github.com/jrochkind/json_attribute/blob/master/lib/json_attribute/model.rb#L154) definition.  I expected the key to be `attribute_def.name`, since the store key represents the storage configuration, and not a model property.
Should this be configurable at least?

**Comment by jrochkind** [comment]
Hmm. I was thinking the serializable representation ought to represent how it will look in the storage. I think this also made implementation quite a bit simpler. 

In general, I think using a store key at all gets kind of confusing, and I think it's best avoided unless you really need it -- use cases I'm thinking of are migrations (temporarily, while you move from one key to another), or maybe in some cases legacy/external databases. 

Can you say more about your use case for store keys, and your use cases/reasons for finding it more convenient if the serializable hash did not yet represent the store key transformation?

**Comment by onomated** [comment]
I'm doing a migration from Mongo.  And in object stores like Mongo, you can save "some" space by using short storage keys, so it a practice I'm carrying over to PG jsonb fields.  Probably a bad idea, as this may result in ambiguity of the purpose of store keys.  But I was generally doing this for space savings due to learnings in the Mongo world.  I'll refrain from using store keys all together to keep this simple.

**Comment by jrochkind** [comment]
I don't think it's actually totally unreasonable to use store keys there, should probably work fine. 

What case did you run into where it was inconvenient that the store keys were already transformed in the serializable_hash?  Or none yet, just surprised you?  Might work out fine as is?

Thank you for the feedback!

**Comment by jrochkind** [comment]
(I actually have no idea if there are space savings there in postgres jsonb, now I'm curious, let me know if you investigate and find the answer. I could see it going either way. jsonb is generally pretty good at minimizing use of space, but I don't know for sure if key length is going to have a per-record  space penalty or not).

**Comment by jrochkind** [comment]
looks like maybe yes. altough there may be a postgres extension to make it no. https://dba.stackexchange.com/questions/161864/do-long-names-for-jsonb-keys-use-more-storage

**Comment by jrochkind** [comment]
I suppose another option is we could make the gem stop using the well-known rails standard `serializable_hash` method, and use it's own `_json_attribute_serializable_hash`, with `serializable_hash` by default just calling it, so you could override `serializable_hash` to do something else if you wanted. But I'd wait for a use case to do that!

**Comment by onomated** [comment]
So I have a Jsonb model:
```ruby
class TzFields
    include JsonAttribute::Model

    json_attribute :name, :string
    json_attribute :offset, :integer
    json_attribute :abbreviation, :string, store_key: 'short'

    validates :name, :offset, presence: true
    validates :offset, numericality: true

    def tzinfo
      TZInfo::Timezone.new(identifier)
    end

    def timezone
      ActiveSupport::TimeZone.new(identifier)
    end

    def serializable_hash
      # Current implementation uses store_key, we actually want the attribute name
      {
        name: self.name,
        offset: self.offset,
        abbreviation: self.abbreviation,
      }
    end
  end
```

With specs that expected json as `{'name': 'tz name', 'offset': 'tz offset', 'abbreviation': 'tz abbreviation'}`.  I opted to store abbreviation as `short`.   My specs fail until I override the serializable hash as above.  So there's a convenient override point.  I guess I'm more questioning the default behavior.
Don't know if you're aware of [Mongoid](http://mongoid.github.io/old/en/mongoid/index.html) but that's what I'm currently migrating from.  Since its the ORM for mongodb, it has embedded docs etc, so a lot of my opinion/experience is fashioned from what is implemented in Mongoid.

**Comment by jrochkind** [comment]
Does overriding like that break db serialization and deserialization behavior, or all is still good?  

Is there any reason your specs can't just be written for actual behavior, is there any reason beyond "the specs are like that" that it's inconvenient?

**Comment by onomated** [comment]
Specs are written to support backwards compatibility with existing API clients during our migration to PG.  So I need the API json response format to remain the same. 
Good point on the db serialization.  I'll take a closer look at that.

**Comment by jrochkind** [comment]
Ah right, I see why you might want API json response keys and db keys to be
different, thanks for spelling it out. Hmm. Maybe the serializable_hash
ought to be the attribute names like you said.

**Comment by onomated** [comment]
Did more digging into this, and you're right.  `serializable_hash` determines the serialization to the DB and is the wrong override point in my case.  My override above resulted in the jsonb structure ignoring the `store_key` specification.   `as_json` is the correct override point in determining the structure of the model's json representation.  Since the current implementation of `as_json` just forwards to `serializable_hash` and both calls support options parameter, maybe adding an option `attribute_name_as_key` that determines whether to use the attribute name or the store key in the generated hash.  Then `as_json` can specify this as default.  What do you think?  I can create a PR showing this.

**Comment by onomated** [comment]
Ok, have my suggestion implemented, and started on specs for it.  Realize that this also has implications on `JsonAttribute::Record` not just `JsonAttribute::Model`.  It is best to leave the current implementation as is, and rely on [ActiveModel Serializers](https://github.com/rails-api/active_model_serializers) for JSON representation.  
Closing this issue.

**Comment by jrochkind** [comment]
Yeah, I was gonna say, I thought making this configurable or different, There Be Dragons. 

If there's an easy way to simply change your serialization, so it doesn't use default serialization_hash, such like you say using ActiveSerializer, I think that's the way go. 

If there isn't, and that looks a pain... I think what I'd want to do in this gem is investigate making it _stop_ using `serializable_hash` for anything, it just wouldn't use that anymore for db serialization and deserialization (at least not on a JsonAttribute::Model object), so that would be available to be overridden however you want without interfering with JsonAttribute. 

That would have to be investigated and played with more to make sure it works out, but that's the direction I'd want to look into first. And if you need it, I can try to look into it!

**Comment by jrochkind** [comment]
And thanks again so much for testing this on some actual production use cases!  I am up for making changes to let it meet your use case more conveniently, your use case is legit -- I just want to be careful doing it, think about the way to do it with the least code complexity and resulting in effects least surprising to people.
