### ISSUE TITLE
json_attribute macro should raise on unrecognized keyword args

### ISSUE THREAD

**Issue by onomated** [jrochkind/json_attribute#5]
If you pass json_attribute an unrecognized keyword, it should immediately raise, to fail fast on wrong keyword args, whether from bad docs or otherwise.  Avoiding the error exhibiting mysteriously like below.  --jrochkind

---------------
### original report:

In my user model, I have two jsonb containers:  `settings` and `extended` defined as follows:

```ruby
class User < ApplicationRecord
  include JsonAttribute::Record
  
  self.default_json_container_attribute = :extended
  json_attribute :timezone, Jsonb::TzFields.to_type
  json_attribute :nickname, type: :string

  json_attribute :setting_1, :boolean, default: true, json_container_attribute: 'settings'
  json_attribute :setting_2, :boolean, default: false, json_container_attribute: 'settings'
  json_attribute :setting_3, :boolean, default: true, json_container_attribute: 'settings'
```

I assign a new settings hash directly to the user to toggle the settings values, similar to so:
```ruby
user = User.first
new_attrs = { 
   email: "someone@example.com", 
   first_name: "new first name", 
   settings: {
      setting_1: false,
      setting_2: true,
      setting_3: false
   } 
}
user.update_attributes!
```

On accessing the `settings` attributes, I still get the default values not the new assigned values, so `user.setting_1` returns `true` instead of the newly assigned `false` value.  
I then inspected the attributes on the `user.attributes`, and the settings are applied correctly to the `settings` jsonb field, but also duplicated in the `extended` jsonb field which was defined as the default jsonb container.  So the attributes look like this:

```ruby
user.attributes = {
  # settings assigned as expected
   settings: {
      setting_1: false,
      setting_2: true,
      setting_3: false,
   },
   # extended has settings fields retaining default values which is should not. 
   extended: {
      setting_1: true,
      setting_2: false,
      setting_3: true,
   },
  ...
}
```

Looks like "mass assignment" of a hash to a jsonb field is supported in the docs.  Is it however supported in the case with multiple jsonb containers?

**Comment by jrochkind** [comment]
That does sound like a bug. The first step to fixing would be making a failing spec. Interested in PRing one? Thanks for taking the gem for a test drive!

**Comment by onomated** [comment]
Turned out to be a documentation bug.  Per field container attribute key should be `container_attribute` not `json_container_attribute` as specified in docs.  This is addressed in PR https://github.com/jrochkind/json_attribute/pull/6

**Comment by jrochkind** [comment]
Hmm, I wonder if it should raise if you pass `json_attribute` an unrecognized keyword, to fail fast on wrong keyword args, whether from bad docs or otherwise.
