### ISSUE TITLE
Access to the parent object

### ISSUE THREAD

**Issue by heldopslippers** [jrochkind/json_attribute#7]
Hi, 

We are currently in the process of implementing the Json_attribute. 
Is there any way to access the parent object when in a JsonAttribute::Record object?

**Comment by jrochkind** [comment]
Hi, thanks for checking it out and providing feedback!

I'm sorry, I'm having trouble understanding your question. Can you provide a bit of code with an example of what you mean by parent object, accessed where?

**Comment by jrochkind** [comment]
Ah, I get it now!  I believe you mean from a JsonAttribute::Model embedded object, it's parent that it's nested in. (which might be another JsonAttribute::Model, or the top-level actual active record model). 

There is not a way to do this at present. 

Can you tell me more about what you were working on when you needed to this, in what sort of situation?

**Comment by jrochkind** [comment]
This isn't in my immediate road map at the moment, I don't think I have a need for it, and it would be a bit tricky to implement. 

But if anyone wants to let me know more about their use case, it might help me prioritize it.
