### ISSUE TITLE
Should JsonAttribute::Model allow undefined attributes?

### ISSUE THREAD

**Issue by jensljungblad** [jrochkind/json_attribute#8]
I would expect `JsonAttribute::Model` to throw an `UnknownAttributeError` if you pass it a property not defined using `json_attribute`. 

```ruby
class Foo
  include JsonAttribute::Record
  json_attribute :bars, Bar.to_type, array: true, default: []
end

class Bar
  include JsonAttribute::Model
  json_attribute :bar, :string
end

Foo.new(bars: [{ baz: 'hello' }])
```

**Comment by jrochkind** [comment]
Hi, thanks for checking this out, and providing feedback!

I have thought of this too. 

But I think there's a case for it doing what it does, when you have 'legacy' data in the database of some kind, and want existing keys to pass through on load/save without being changed, even if they aren't declared with `json_attribute`. 

But I was thinking it might have to be configurable (on a per-model basis).  I was thinking `allow` (do what it does now, pass through), `raise` (what you suggest), or `strip` (silently remove/ignore them). 

What do you think?  And can you provide more context about the usage scenario you were thinking about, where you'd expect it to raise?

**Comment by jensljungblad** [comment]
That sounds good. I ended up using something different, JSON Schemas, since I was mostly after having a schema for my `jsonb`. But in that standard there is an `additionalProperties` that you can set to true or false on objects. If set to true, validation fails if you try and set properties not defined in the schema. [This gem](https://github.com/ruby-json-schema/json-schema) has support for that property, for instance.

**Comment by jrochkind** [comment]
Thanks for feedback!  Interesting, your main goal was enforcing schema on the jsonb. That's a different place than I'm coming from, but it should be possible to move a bit towards that use case -- although I have no plans to support actual JSON Schema at present, doing things differently. 

How did you end up setting things up to enforce a json schema on jsonb data?

**Comment by jensljungblad** [comment]
I used this gem: https://github.com/ruby-json-schema/json-schema together with a custom validator that looks like this:

```ruby
class JsonValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    errors = JSON::Validator.fully_validate(
      options[:schema],
      value,
      strict: true
    )

    return if errors.empty?

    errors.each do |error|
      record.errors.add(attribute, error)
    end
  end
end
```

Which I then use like so:

```ruby
validates :data, json: {
  schema: Rails.root.join('pathh', 'to', 'schema.json').to_s
}
```

**Comment by jrochkind** [comment]
Nice thanks @jensljungblad .

It occurs to me that you could do exactly what you just showed _with_ this gem. You should be able to add those json-schema-based validations to your base ActiveRecord::Model, and/or to individual embedded `JsonAttribute::Model`s.  And it should all just work, with just the code that's here now in this gem. 

I expect it will, but if it _doesn't_ then I'd want to fix it so it does. 

But if you don't need/want anything else in this gem and you only want schema validation -- I think what you've done is just right!  If you want both... you should be able to do it.

**Comment by jrochkind** [comment]
Ah, but I see your suggestion... I suppose another step would be, like you suggest, automatically making the `json_attribute` declarations _from_ a json schema. So you don't need to repeat the declarations here. 

That would be pretty neat, and I agree _probably_ ought to be possible, although tricky, but it's not in my personal road map at present. 

Of course, you (or anyone) could experiment with that without actual support from the gem, you can write your own logic that takes a json_schema and turns it into some ruby code to call `SomeModelClass.json_attribute whatever` and maybe define `JsonAttribute::Model` classes too (they can be anonymous). Should be able to do that without requiring any changes here, if you can figure out that code. But it would be tricky, and if you don't actually need it for your uses... But if you or anyone else _does_ do it in a reliable way, I'd def be interested in a PR to add that feature!
